/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;


import javax.swing.JOptionPane;

/**
 *
 * @author Sahir Reyes
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tipoDeAcceso = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mostrarContraseña = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        textoContraseña = new javax.swing.JPasswordField();
        textoUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipoDeAcceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Repartidor", "Administrador" }));
        tipoDeAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDeAccesoActionPerformed(evt);
            }
        });
        jPanel1.add(tipoDeAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 138, 132, -1));

        jLabel5.setText("Acceso:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 141, 60, -1));

        jLabel4.setText("Nombre de la paqueteria");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 47, -1, -1));

        mostrarContraseña.setText("Mostrar contraseña");
        mostrarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 306, -1, -1));

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 370, -1, -1));

        textoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(textoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 266, 211, -1));

        textoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(textoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 200, 211, -1));

        jLabel3.setText("Contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 269, -1, -1));

        jLabel2.setText("Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 203, 62, -1));

        jLabel1.setText("Inicio de sesión");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 81, -1, 26));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (!textoUsuario.getText().isEmpty() && !textoContraseña.getText().isEmpty()) {
            int tipoDeAccess = tipoDeAcceso.getSelectedItem().toString().equals("Administrador")?1:2;
            Usuario usuario = new Usuario(textoUsuario.getText(),textoContraseña.getText(),tipoDeAccess);
            if (usuario.autentificar()) {
                JOptionPane.showMessageDialog(this, "Bienvenido");
                this.dispose();
                if (tipoDeAccess==1) {
                    InterfazAdmin interfazAdmin = new InterfazAdmin();
                    interfazAdmin.setVisible(true);
                }else{
                    InterfazRepartidor interfazRepartidor = new InterfazRepartidor();
                    interfazRepartidor.setVisible(true);
                }
                
            }else{
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecta");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Falta ingresar contraseña");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mostrarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarContraseñaActionPerformed
        if(mostrarContraseña.isSelected()){
            textoContraseña.setEchoChar((char)0);
        }else{
            textoContraseña.setEchoChar('*');
        }
            
    }//GEN-LAST:event_mostrarContraseñaActionPerformed

    private void textoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoContraseñaActionPerformed

    private void tipoDeAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDeAccesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoDeAccesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox mostrarContraseña;
    private javax.swing.JPasswordField textoContraseña;
    private javax.swing.JTextField textoUsuario;
    private javax.swing.JComboBox<String> tipoDeAcceso;
    // End of variables declaration//GEN-END:variables
}
